defaults:
  - base.yaml

algorithm: sac

gamma: 0.99
twin_q: true
initial_alpha: 1.0
target_entropy: auto
tau: 0.005
target_network_update_freq: 1
n_step: 1

train_batch_size: 256
num_steps_sampled_before_learning_starts: 1000

optimization:
  actor_learning_rate: 3.0e-4
  critic_learning_rate: 3.0e-4
  entropy_learning_rate: 3.0e-4

replay_buffer_config:
  type: MultiAgentReplayBuffer
  capacity: 1000000
  replay_sequence_length: 1
